title: Hangfire
description: "An easy way to perform background processing in .NET and .NET Core applications. No separate process required, uses persistent storage."
url: https://www.hangfire.io
cdn: 

author:
  name: 'odinserj'
  url:  https://twitter.com/odinserj

github_repo:   https://github.com/HangfireIO/HangfireIO.github.io
github_branch: master

hyvor_website:         8471
hyvor_show_comment_count: true

# Windows environments
# highlighter: rouge

kramdown:
  auto_ids: true
  input:    GFM

permalink: /blog/:year/:month/:day/:title.html

paginate:      5
paginate_path: "blog/page:num/"

defaults:
  -   
   scope:
     type: "pages"
   values:
     permalink: /:path/:basename:output_ext
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      active: blog
  -
    scope: 
      path: ""
      type: "drafts"
    values:
      layout: "post"

gems:
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate
